### PR TITLE
CI/CD

### PR DESCRIPTION
**Pull request by AlexXin14**
Create the Jenkins file for the CI part.

### CODE REVIEW

**Comment by NorrisWu0** [comment]
You can merge latest `develop` into your branch now, there are a few example unit test ready there.

**Comment by AlexXin14** [comment]
> You can merge latest `develop` into your branch now, there are a few example unit test ready there.

I pull from the `develop` branch this morning. I do not think you integrate the "yarn test" script into the package.json yet.

**Comment by NorrisWu0** [comment]
Okay, develop should have the sample unit test, you can merge `develop` again now. Otherwise, I'm happy to merge this.

**Comment by yuanrenc** [comment]
approved

**Review by yuanrenc — APPROVED** [review]

**Pull request closed without merging**
